# Run pyCycle Tests
name: pyCycle Tests

on:
  # Trigger on push or pull request events for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allow running the workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel any existing CI runs if we push to this branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test_pycycle:

    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        include:

          # test baseline versions on Ubuntu
          - NAME: Ubuntu Baseline
            OS: ubuntu-24.04
            OPENMDAO_PIXI_ENVIRONMENT: 'py314'
            OPENMDAO_INSTALL_FROM: 'pypi'
            OPENMDAO: ''
            COVERAGE: true

          # latest versions of openmdao/dymos
          - NAME: MacOS Baseline
            OS: macos-latest
            OPENMDAO_PIXI_ENVIRONMENT: 'py314'
            OPENMDAO_INSTALL_FROM: 'pypi'
            OPENMDAO: ''
            COVERAGE: true

          # latest versions of openmdao/dymos
          # Coverage currently has some problems in windows, according to the openmdao workflows.
          - NAME: Windows Baseline
            OS: windows-latest
            OPENMDAO_PIXI_ENVIRONMENT: 'py314'
            OPENMDAO_INSTALL_FROM: 'pypi'
            OPENMDAO: ''
            COVERAGE: false

          # oldest supported versions of openmdao/dymos
          # Note: bugfixes sometimes require incrementing the minimal version of openmdao or dymos.
          - NAME: Ubuntu Oldest
            OS: ubuntu-24.04
            OPENMDAO_PIXI_ENVIRONMENT: 'py311'
            OPENMDAO_INSTALL_FROM: 'pypi'
            OPENMDAO: '3.41.0'
            COVERAGE: true

          # test with latest/development versions
          # only run when selected via workflow_dispatch
          - NAME: OpenMDAO Dev
            OS: ubuntu-24.04
            OPENMDAO_PIXI_ENVIRONMENT: 'py314'
            OPENMDAO_INSTALL_FROM: 'github'
            OPENMDAO: ''


    runs-on: ${{ matrix.OS }}

    name: ${{ matrix.NAME }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Display run details
        run: |
          echo "============================================================="
          echo "Run #${GITHUB_RUN_NUMBER}"
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Testing: ${GITHUB_REPOSITORY}"
          echo "Triggered by: ${GITHUB_EVENT_NAME}"
          echo "Initiated by: ${GITHUB_ACTOR}"
          echo "============================================================="

      - name: Checkout Aviary
        uses: actions/checkout@v6

      - name: 'Setup OpenMDAO pixi Environment'
        id: setup_pixi_environment
        uses: OpenMDAO/OpenMDAO/.github/actions/setup_openmdao_pixi@master
        with:
          environment: '${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }}'
          openmdao_install_from: '${{ matrix.OPENMDAO_INSTALL_FROM }}'
          openmdao_version: '${{ matrix.OPENMDAO }}'

      - name: Install pyCycle
        run: |
          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
          echo "============================================================="
          echo "Install pyCycle"
          echo "============================================================="
          python -m pip install -e .[all]

      - name: Run tests
        id: run_tests
        run: |
          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
          echo "============================================================="
          echo "Run tests (from directory other than repo root)"
          echo "============================================================="
          cd $HOME
          RPT_FILE=`pwd`/deprecations.txt
          echo "RPT_FILE=$RPT_FILE" >> $GITHUB_ENV
          testflo -n 1 pycycle --timeout=240 --show_skipped --deprecations_report=$RPT_FILE --coverage --coverpkg pycycle --durations=20

      - name: Deprecations Report
        id: deprecations_report
        continue-on-error: true
        run: |
          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
          echo "============================================================="
          echo "Display deprecations report"
          echo "============================================================="
          cat $RPT_FILE

          echo 'summary<<EOF' >> $GITHUB_OUTPUT
          head -n 6 $RPT_FILE | cut -d':' -f 1 >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

          grep '^0 unique deprecation warnings' $RPT_FILE

      - name: Check NumPy 2.0 Compatibility
        run: |
          eval "$(pixi shell-hook -e ${{ matrix.OPENMDAO_PIXI_ENVIRONMENT }} --manifest-path=${{ env.PIXI_MANIFEST }})"
          echo "============================================================="
          echo "Check code for NumPy 2.0 compatibility"
          echo "See: https://numpy.org/devdocs/numpy_2_0_migration_guide.html"
          echo "============================================================="
          python -m pip install ruff
          cd ${{ github.workspace }}
          ruff check . --select NPY201

      - name: Slack unit test failure
        if: steps.run_tests.outcome == 'failure'
        uses: act10ns/slack@v2.0.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ steps.run_tests.outcome }}
          message: |
            `pyCycle`: Unit testing failed on `${{ matrix.NAME }}` build.
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Slack deprecation warnings
        if: steps.deprecations_report.outcome == 'failure' && matrix.NAME == 'Ubuntu Baseline'
        uses: act10ns/slack@v2.0.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: 'warning'
          message: |
            `pyCycle`: Deprecations were detected on `${{ matrix.NAME }}` build.
            ```${{ steps.deprecations_report.outputs.summary }}```
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
